export { default as HomeScreen } from './Home'
export { default as Pacientes } from './Pacientes'
export { default as Login } from './Login'
export { default as FichaClinica } from './FichaClinica'
export { default as Turnos } from './Turnos'
